### ISSUE TITLE
Bluetooth is able to turn on but doesn't transmit sound to the receiver

### ISSUE THREAD

**Issue by ragilmalik** [Magisk-Modules-Repo/gjf_bt#4]
After installing this, my bluetooth is unable to transmit sound to any device.
I tried to disable, uninstall, install again then uninstall again and still nothing happens.
Tried to uninstall then install magisk and still, nada.
Do you know how to fix this ?

I am using poco F1 with Pixel experince pie. I know the answer is to flash the ROM again but i didn't back up my data before trying this module.

Thanks.

**Comment by gjf** [comment]
Installing a module in Magisk in fact does not change anything in system partition - that's how Magisk is working.
Once you remove the module everything should be the same because all the files in systme remains the same.
Try to boot in Core mode of Magisk (no modules atre activated in this mode). If it won't help - I have no idea what yiu did with your system.
